package com.example;
/*
 * 예외 처리 Exception handling 
 * 
 * 
 */
public class TryCatchExample {

	public static void main(String[] args) {
		
		int x = 0;
		String str = null;
		
		try {
			int result = 10/x;	// ArithmeticException		
			
			str.charAt(0);		// NullPointerException
			
		} catch (ArithmeticException e) {
			System.out.println("0으로 나눌 수 없습니다.");
//			e.printStackTrace();	// error print 
		} catch (NullPointerException e) {
			System.out.println("Null 입니다. Null은 연산할 수 없습니다.");
		}
		
		System.out.println("End.. ");
		
	}
	
	
	public static void main2(String[] args) {

		
		System.out.println("start");
		System.err.println("start");		// err type print
		System.out.println("start");
		
		try {
			int result = 10/0;		// runtime exception을 조상으로 둔 예외클래스. 
		} catch (ArithmeticException e) {
			
		}
		
		
		
		
		System.out.println("End.. ");
		
	}

}
